### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by angelozerr** [RReverser/acorn-jsx#30]
@RReverser I'm starting to develop a tern plugin for React https://github.com/angelozerr/tern-react

For the moment I can initialize acorn used inside tern with acorn-jsx. 

As tern can work with Web Browser, I need to browserify the acorn-jsx. It should be very cool if you could do the same thing than [acorn/dist ](https://github.com/marijnh/acorn/tree/master/dist) by providing a file **build-acorn_jsx.js** like [build-acorn.js](https://github.com/marijnh/acorn/blob/master/bin/build-acorn.js).

Thanks!

**Comment by RReverser** [comment]
It doesn't make sense to publish Browserified / Webpacked / ... versions for each plugin (or any npm packages) IMO. If you want to use it, why not just install modules as regular CommonJS and then bundle them together on the side of project instead of forcing package authors to prodive precompiled versions and include separate `script`s on page?

**Comment by angelozerr** [comment]
Acorn does that, so I tell me why acorn-jsx doesn't do that?

**Comment by RReverser** [comment]
Acorn is not a plugin but a generic library. It's like asking each jQuery plugin to provide browserified version while jQuery officially recommends using npm for plugins :)
