### ISSUE TITLE
Flow type support

### ISSUE THREAD

**Issue by kittens** [RReverser/acorn-jsx#8]
@RReverser Would you be interested in supporting [flow types](http://flowtype.org/)? I think it'd be a good feature to add, especially since it can be used in conjunction with JSX. I can give this a go if this is something that you're interested in. Would be aiming to pass the entire [esprima-fb type test suite](https://github.com/facebook/esprima/blob/fb-harmony/test/fbtest.js#L77-257).

**Comment by sebmck** [comment]
@RReverser I see that `_lt` and `_gt` was changed to a general `_relational`, how do I determine between the two?

**Comment by davidpfahler** [comment]
@RReverser @sebmck What's the status? I see that babel has a [flow transformer](https://babeljs.io/docs/advanced/transformers/other/flow/), so is this solved? If not, how can I help to move this forward?

**Comment by sebmck** [comment]
@davidpfahler Babel has a Flow plugin but it relies on the Babel Acorn fork.

**Comment by RReverser** [comment]
@sebmck Btw now that we have both JSX and Flow implemented as plugins - maybe time to add Flow support to this repo? Should be easier to maintain (since I'll be able to update all the methods at once as soon as breaking version of Acorn appears).

**Comment by sebmck** [comment]
@RReverser It still relies on the lookahead I patched into Acorn. I remain unconvinced that there are performance implications with having lookaheads since Esprima is already much faster and simpler with them. I still need to update the Babel internal method names to match the new ones that I added to Acorn core.

**Comment by RReverser** [comment]
@sebmck As far as I know, @marijnh is now also convinced and interested in lookaheads in Acorn. If you're saying you already have those, feel free to PR.

As for the second part - IIUC, you need to do that with JSX as well, so shouldn't make big difference if we keep everything in one place.

**Comment by sebmck** [comment]
@RReverser Sure, I'm actually super keen on getting this into `acorn-jsx` as it's one step further towards not having an internal fork. I'm not super comfortable with my lookahead implementation as it's [extremely hacky](https://github.com/babel/babel/blob/master/src/acorn/src/lookahead.js). It's necessary for the Flow plugin due to [grouped types](https://github.com/babel/babel/blob/master/src/acorn/plugins/flow.js#L480). I've tried implementing it without but have never been able to finish it as you have to pass the parsed expression around and you can't really "resume parsing".
